# Generated by Django 4.1.5 on 2023-01-29 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('paradigm', models.CharField(max_length=200)),
                ('author', models.CharField(max_length=100)),
            ],
        ),
    ]
